/**
 * The workspace map (SPEC-integration §C6): a generated Mermaid block built from
 * `keel.json` and the links between cards, regenerated on command only.
 * Pure TypeScript.
 */

import type { Card } from './cards';
import { findFences, replaceFenceBody, type Fence } from './fence';
import type { KeelManifest } from './workspace';

export const MAP_MARKER = '%% generated by keel-diagram from keel.json; edit the manifest, not this block';

export type MapDirection = 'LR' | 'TD';

export interface MapInput {
	manifest: KeelManifest;
	/** Every card under the workspace root, with the project each sits in (null = workspace level). */
	cards: { card: Card; project: string | null }[];
	/** Prefix → project, from `board.json` manifests. Cards fill in what this lacks. */
	prefixProjects?: Record<string, string>;
	direction?: MapDirection;
}

/** `git@github.com:Owner/repo.git` or `https://github.com/Owner/repo.git` → `Owner/repo`. */
export function repoShortName(url: string): string {
	const m = /[:/]([^/:]+\/[^/]+?)(?:\.git)?\/?$/.exec(url.trim());
	return m?.[1] ?? url.trim();
}

function nodeId(prefix: string, raw: string): string {
	return prefix + raw.replace(/[^A-Za-z0-9]/g, '_');
}

function label(text: string): string {
	return `"${text.replace(/"/g, '#quot;')}"`;
}

/**
 * Builds the body of the map block: the marker line, then a flowchart with the
 * workspace, one subgraph per project holding its repos, and the cards that take
 * part in a link, with an edge per link.
 */
export function buildWorkspaceMap(input: MapInput): string {
	const { manifest } = input;
	const dir = input.direction ?? 'LR';
	const projects = manifest.projects ?? [];
	const out: string[] = [MAP_MARKER, `flowchart ${dir}`];
	const ws = 'ws';
	out.push(`    ${ws}[${label(manifest.name ?? 'workspace')}]`);

	// Cards that appear: every source of a link and every target.
	const byId = new Map(input.cards.map((c) => [c.card.id, c]));
	const prefixProjects = new Map<string, string>(Object.entries(input.prefixProjects ?? {}));
	for (const { card, project } of input.cards) if (project && !prefixProjects.has(card.prefix)) prefixProjects.set(card.prefix, project);

	const shown = new Map<string, { id: string; title: string; project: string | null }>();
	const edges: [string, string][] = [];
	for (const { card, project } of input.cards) {
		if (card.links.length === 0) continue;
		shown.set(card.id, { id: card.id, title: card.title, project });
		for (const to of card.links) {
			const target = byId.get(to);
			if (!shown.has(to)) {
				shown.set(to, {
					id: to,
					title: target?.card.title ?? '',
					project: target?.project ?? prefixProjects.get(to.slice(0, to.indexOf('-'))) ?? null,
				});
			}
			edges.push([card.id, to]);
		}
	}

	const cardLine = (c: { id: string; title: string }, indent: string) =>
		`${indent}${nodeId('c_', c.id)}[${label(c.title ? `${c.id} ${c.title}` : c.id)}]`;

	for (const project of projects) {
		const pid = nodeId('p_', project.name);
		out.push(`    subgraph ${pid}[${label(project.name)}]`);
		(project.repos ?? []).forEach((repo, i) => {
			if (!repo.url) return;
			out.push(`        ${nodeId(`r_${i}_`, project.name)}[${label(repoShortName(repo.url))}]`);
		});
		for (const c of shown.values()) if (c.project === project.name) out.push(cardLine(c, '        '));
		out.push('    end');
	}
	for (const c of shown.values()) if (c.project === null || !projects.some((p) => p.name === c.project)) out.push(cardLine(c, '    '));

	for (const project of projects) out.push(`    ${ws} --> ${nodeId('p_', project.name)}`);
	for (const [from, to] of edges) out.push(`    ${nodeId('c_', from)} --> ${nodeId('c_', to)}`);
	return out.join('\n');
}

/** Wraps a map body in a mermaid fence. */
export function wrapMapFence(body: string): string {
	return '```mermaid\n' + body + '\n```';
}

/** Every mermaid fence whose first line is the marker. */
export function findMapFences(text: string): Fence[] {
	return findFences(text).filter((f) => f.lang === 'mermaid' && (f.body.split('\n')[0] ?? '').trim() === MAP_MARKER);
}

/** Replaces the body of every marked block with `body`. */
export function regenerateMaps(text: string, body: string): { text: string; count: number } {
	const fences = findMapFences(text);
	let out = text;
	for (const fence of [...fences].reverse()) out = replaceFenceBody(out, fence, body);
	return { text: out, count: fences.length };
}
